aptitude install -y  texlive-base
aptitude install -y  texlive-extra-utils
aptitude install -y  texlive-font-utils
aptitude install -y  texlive-fonts-recommended
aptitude install -y  texlive-generic-extra
aptitude install -y  texlive-generic-recommended
aptitude install -y  texlive-latex-base
aptitude install -y  texlive-latex-extra
aptitude install -y  texlive-latex-recommended
aptitude install -y  texlive-pictures
aptitude install -y  texlive-pstricks
aptitude install -y  texlive-xetex
